import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import Provider from "./provider";
import GlobalTransitionLoader from "@/components/GlobalTransitionLoader/GlobalTransitionLoader";

export const Peyda = localFont({
  src: "../assets/fonts/Peyda.ttf",
});

export const metadata: Metadata = {
  title: "Delta Estate",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="fa" dir="rtl">
      <body className={`${Peyda.className} antialiased`}>
        <Provider>
          <GlobalTransitionLoader />
          {children}
        </Provider>
      </body>
    </html>
  );
}
